// <auto-generated/>
//
// This file is generated by ActivityMonitorSimpleSenderExtension.Group-Gen.tt
//
using System;
using System.Runtime.CompilerServices;
#nullable enable

namespace CK.Core
{
    public static partial class ActivityMonitorSimpleSenderExtension
    {
		 
		/// <summary>
        /// Opens a <see cref="LogLevel.Debug"/> group with an exception. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl( MethodImplOptions.AggressiveInlining )]
        public static IDisposableGroup OpenDebug( this IActivityMonitor monitor, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Debug, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Debug | LogLevel.IsFiltered, finalTags, null, ex, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Debug"/> group with a text message. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl( MethodImplOptions.AggressiveInlining )]
        public static IDisposableGroup OpenDebug( this IActivityMonitor monitor, string text, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Debug, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Debug | LogLevel.IsFiltered, finalTags, text, null, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Debug"/> group with a text message associated to an exception. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenDebug( this IActivityMonitor monitor, string text, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Debug, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Debug | LogLevel.IsFiltered, finalTags, text, ex, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

        #region Debug with tags.

		/// <summary>
        /// Opens a <see cref="LogLevel.Debug"/> group with an exception and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IDisposableGroup OpenDebug( this IActivityMonitor monitor, CKTrait tags, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Debug, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Debug | LogLevel.IsFiltered, finalTags, null, ex, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Debug"/> group with a text message and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenDebug( this IActivityMonitor monitor, CKTrait tags, string text, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Debug, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Debug | LogLevel.IsFiltered, finalTags, text, null, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Debug"/> group with a text message associated to an exception and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenDebug( this IActivityMonitor monitor, CKTrait tags, string text, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Debug, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Debug | LogLevel.IsFiltered, finalTags, text, ex, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

        #endregion

		 
		/// <summary>
        /// Opens a <see cref="LogLevel.Trace"/> group with an exception. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl( MethodImplOptions.AggressiveInlining )]
        public static IDisposableGroup OpenTrace( this IActivityMonitor monitor, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Trace, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Trace | LogLevel.IsFiltered, finalTags, null, ex, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Trace"/> group with a text message. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl( MethodImplOptions.AggressiveInlining )]
        public static IDisposableGroup OpenTrace( this IActivityMonitor monitor, string text, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Trace, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Trace | LogLevel.IsFiltered, finalTags, text, null, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Trace"/> group with a text message associated to an exception. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenTrace( this IActivityMonitor monitor, string text, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Trace, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Trace | LogLevel.IsFiltered, finalTags, text, ex, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

        #region Trace with tags.

		/// <summary>
        /// Opens a <see cref="LogLevel.Trace"/> group with an exception and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IDisposableGroup OpenTrace( this IActivityMonitor monitor, CKTrait tags, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Trace, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Trace | LogLevel.IsFiltered, finalTags, null, ex, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Trace"/> group with a text message and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenTrace( this IActivityMonitor monitor, CKTrait tags, string text, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Trace, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Trace | LogLevel.IsFiltered, finalTags, text, null, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Trace"/> group with a text message associated to an exception and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenTrace( this IActivityMonitor monitor, CKTrait tags, string text, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Trace, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Trace | LogLevel.IsFiltered, finalTags, text, ex, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

        #endregion

		 
		/// <summary>
        /// Opens a <see cref="LogLevel.Info"/> group with an exception. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl( MethodImplOptions.AggressiveInlining )]
        public static IDisposableGroup OpenInfo( this IActivityMonitor monitor, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Info, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Info | LogLevel.IsFiltered, finalTags, null, ex, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Info"/> group with a text message. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl( MethodImplOptions.AggressiveInlining )]
        public static IDisposableGroup OpenInfo( this IActivityMonitor monitor, string text, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Info, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Info | LogLevel.IsFiltered, finalTags, text, null, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Info"/> group with a text message associated to an exception. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenInfo( this IActivityMonitor monitor, string text, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Info, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Info | LogLevel.IsFiltered, finalTags, text, ex, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

        #region Info with tags.

		/// <summary>
        /// Opens a <see cref="LogLevel.Info"/> group with an exception and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IDisposableGroup OpenInfo( this IActivityMonitor monitor, CKTrait tags, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Info, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Info | LogLevel.IsFiltered, finalTags, null, ex, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Info"/> group with a text message and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenInfo( this IActivityMonitor monitor, CKTrait tags, string text, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Info, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Info | LogLevel.IsFiltered, finalTags, text, null, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Info"/> group with a text message associated to an exception and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenInfo( this IActivityMonitor monitor, CKTrait tags, string text, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Info, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Info | LogLevel.IsFiltered, finalTags, text, ex, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

        #endregion

		 
		/// <summary>
        /// Opens a <see cref="LogLevel.Warn"/> group with an exception. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl( MethodImplOptions.AggressiveInlining )]
        public static IDisposableGroup OpenWarn( this IActivityMonitor monitor, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Warn, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Warn | LogLevel.IsFiltered, finalTags, null, ex, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Warn"/> group with a text message. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl( MethodImplOptions.AggressiveInlining )]
        public static IDisposableGroup OpenWarn( this IActivityMonitor monitor, string text, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Warn, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Warn | LogLevel.IsFiltered, finalTags, text, null, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Warn"/> group with a text message associated to an exception. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenWarn( this IActivityMonitor monitor, string text, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Warn, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Warn | LogLevel.IsFiltered, finalTags, text, ex, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

        #region Warn with tags.

		/// <summary>
        /// Opens a <see cref="LogLevel.Warn"/> group with an exception and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IDisposableGroup OpenWarn( this IActivityMonitor monitor, CKTrait tags, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Warn, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Warn | LogLevel.IsFiltered, finalTags, null, ex, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Warn"/> group with a text message and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenWarn( this IActivityMonitor monitor, CKTrait tags, string text, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Warn, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Warn | LogLevel.IsFiltered, finalTags, text, null, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Warn"/> group with a text message associated to an exception and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenWarn( this IActivityMonitor monitor, CKTrait tags, string text, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Warn, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Warn | LogLevel.IsFiltered, finalTags, text, ex, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

        #endregion

		 
		/// <summary>
        /// Opens a <see cref="LogLevel.Error"/> group with an exception. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl( MethodImplOptions.AggressiveInlining )]
        public static IDisposableGroup OpenError( this IActivityMonitor monitor, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Error, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Error | LogLevel.IsFiltered, finalTags, null, ex, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Error"/> group with a text message. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl( MethodImplOptions.AggressiveInlining )]
        public static IDisposableGroup OpenError( this IActivityMonitor monitor, string text, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Error, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Error | LogLevel.IsFiltered, finalTags, text, null, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Error"/> group with a text message associated to an exception. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenError( this IActivityMonitor monitor, string text, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Error, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Error | LogLevel.IsFiltered, finalTags, text, ex, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

        #region Error with tags.

		/// <summary>
        /// Opens a <see cref="LogLevel.Error"/> group with an exception and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IDisposableGroup OpenError( this IActivityMonitor monitor, CKTrait tags, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Error, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Error | LogLevel.IsFiltered, finalTags, null, ex, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Error"/> group with a text message and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenError( this IActivityMonitor monitor, CKTrait tags, string text, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Error, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Error | LogLevel.IsFiltered, finalTags, text, null, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Error"/> group with a text message associated to an exception and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenError( this IActivityMonitor monitor, CKTrait tags, string text, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Error, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Error | LogLevel.IsFiltered, finalTags, text, ex, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

        #endregion

		 
		/// <summary>
        /// Opens a <see cref="LogLevel.Fatal"/> group with an exception. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl( MethodImplOptions.AggressiveInlining )]
        public static IDisposableGroup OpenFatal( this IActivityMonitor monitor, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Fatal, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Fatal | LogLevel.IsFiltered, finalTags, null, ex, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Fatal"/> group with a text message. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl( MethodImplOptions.AggressiveInlining )]
        public static IDisposableGroup OpenFatal( this IActivityMonitor monitor, string text, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Fatal, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Fatal | LogLevel.IsFiltered, finalTags, text, null, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Fatal"/> group with a text message associated to an exception. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <see cref="IActivityMonitor.AutoTags"/>),
        /// it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenFatal( this IActivityMonitor monitor, string text, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Fatal, null, out var finalTags )
                                                ? new ActivityMonitorLogData( LogLevel.Fatal | LogLevel.IsFiltered, finalTags, text, ex, fileName, lineNumber )
                                                : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

        #region Fatal with tags.

		/// <summary>
        /// Opens a <see cref="LogLevel.Fatal"/> group with an exception and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IDisposableGroup OpenFatal( this IActivityMonitor monitor, CKTrait tags, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Fatal, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Fatal | LogLevel.IsFiltered, finalTags, null, ex, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Fatal"/> group with a text message and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenFatal( this IActivityMonitor monitor, CKTrait tags, string text, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Fatal, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Fatal | LogLevel.IsFiltered, finalTags, text, null, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

		/// <summary>
        /// Opens a <see cref="LogLevel.Fatal"/> group with a text message associated to an exception and tags. 
        /// Regardless of whether it will be emitted or not (this depends on <see cref="IActivityMonitor.ActualFilter"/>, 
        /// the global default <see cref="ActivityMonitor.DefaultFilter"/> and may also depend on <paramref name="tags"/> and
        /// <see cref="IActivityMonitor.AutoTags"/>), it must always be closed.
        /// </summary>
        /// <param name="monitor">This <see cref="IActivityMonitor"/>.</param>
        /// <param name="tags">The tags for this log.</param>
        /// <param name="text">The text to log.</param>
        /// <param name="ex">The exception to log.</param>
        /// <param name="lineNumber">Line number in the source file (automatically injected by C# compiler).</param>
        /// <param name="fileName">Source file name of the emitter (automatically injected by C# compiler).</param>
        /// <returns>A disposable object that can be used to set a function that provides a conclusion text and/or close the group.</returns>
        public static IDisposableGroup OpenFatal( this IActivityMonitor monitor, CKTrait tags, string text, Exception ex, [CallerLineNumber]int lineNumber = 0, [CallerFilePath]string? fileName = null )
        {
            var d = monitor.ShouldLogGroup( LogLevel.Fatal, tags, out var finalTags )
                                               ? new ActivityMonitorLogData( LogLevel.Fatal | LogLevel.IsFiltered, finalTags, text, ex, fileName, lineNumber )
                                               : default;
            return monitor.UnfilteredOpenGroup( ref d );
        }

        #endregion

		 
	}
}

